name: .NET Build

on:
  push:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      working-directory: ./usue online tests
      run: dotnet restore "usue online tests.csproj"

    - name: Build
      working-directory: ./usue online tests
      run: dotnet build "usue online tests.csproj" --no-restore -c Release
